server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql_1:3306/prod_db
    username: root
    password: root123414
    driver-class-name: com.mysql.cj.jdbc.Driver
custom:
  fileDirPath: /usr/file